- hosts: 127.0.0.1
  become: yes
  become_method: sudo
  tasks:
  - name: ensure Java Runtime Environment is installed
    apt: 
      name: default-jre 
      state: present 
#      update_cache: yes
  - name: create calculator directory
    file: 
      path: /var/calculator
      state: directory
  - name: copy calculator starting script
    copy: 
      src: calculator.sh 
      dest: /var/calculator/calculator.sh
      mode: a+x
  - name: configure Calculator as a service
    file: 
      path: /etc/init.d/calculator
      state: link 
      force: yes 
      src: /var/calculator/calculator.sh
  - name: copy Calculator
    copy:
      src: /home/itam/calculator/target/calculator-0.0.1-SNAPSHOT.jar 
      dest: /var/calculator/calculator.jar
      mode: a+x
    notify:
    - restart Calculator
  handlers:
  - name: restart Calculator
    service: 
      name: calculator
      enabled: yes 
      state: started
